### ISSUE TITLE
TLS handshake timeout while sending to ServiceNow

### ISSUE THREAD

**Issue by kotchaosu** [FXinnovation/alertmanager-webhook-servicenow#36]
For version 1.6.0, while using admin credentials to send new incident to ServiceNow I'm getting following errors:

```
time="2021-04-01T14:44:54Z" level=error msg="Error sending the request. Get https://my-instance.service-now.com/api/now/v2/table/incident?correlation_id=1925d04d41e456c3c337ff6896e7fdae: net/http: TLS handshake timeout" source="servicenow.go:147"
time="2021-04-01T14:44:54Z" level=error msg="Error while getting the incident. Get https://my-instance.service-now.com/api/now/v2/table/incident?correlation_id=1925d04d41e456c3c337ff6896e7fdae: net/http: TLS handshake timeout" source="servicenow.go:213"
time="2021-04-01T14:44:54Z" level=error msg="Error managing incident from alert : Get https://my-instance.service-now.com/api/now/v2/table/incident?correlation_id=1925d04d41e456c3c337ff6896e7fdae: net/http: TLS handshake timeout" source="main.go:160"
```

For the following configuration:

```
service_now:
  instance_name: "my-instance"
  user_name: "admin"
  password: "xxx"
  table_name: "incident"

workflow:
  incident_group_key_field: "correlation_id"
  no_update_states: [6,7,8]
  incident_update_fields: ["comments"]

default_incident:
  assignment_group: "{{.CommonAnnotations.assignment_group}}"
  category: "Failure"
  cmdb_ci: "{{.CommonAnnotations.cmdb_ci}}"
  comments: "Alerts list:\n\n{{ range .Alerts }}[{{ .Status }}] {{.StartsAt}} {{.Labels.alertname}}\n{{.Annotations.description}}\n\n{{ end }}"
  company: "Agrest Corp"
  contact_type : "abba@zabba.pl"
  description: "Received alerts from AlertManager at {{.ExternalURL}} (\"{{.Receiver}}\" receiver configuration) with common descriptions:\n\n{{.CommonAnnotations.description}}"
  impact: "2"
  short_description: "Alerts from group: {{ range $key, $val := .GroupLabels}}{{ $key }}:{{ $val }} {{end}}"
  subcategory: "Missing Part"
  urgency: "{{.CommonAnnotations.severity}}"
```

Sending incidents via curl works correctly in my case for both v1 and v2 API endpoints:

```
curl "https://my-instance.service-now.com/api/now/table/incident" \
--request POST \
--header "Accept:application/json" \
--header "Content-Type:application/json" \
--data '{"short_description":"test description","description":"test long description","state":1}' \
--user 'admin':'xxx'
```
